### ISSUE TITLE
Compatibility with 4.6?

### ISSUE THREAD

**Issue by danaskallman** [tadpolecc/cc.tadpole.petitionemail#6]
I was doing some test and seeing if extension works with 4.6. When enabled and I create a new petition it just gives me a blank screen. What's needed to be done to make extension compatible with 4.6? 

Also nothing that this was on WP CMS.

**Comment by kcristiano** [comment]
I have confirmed on a clean 4.6 build using Buildkit.  Nothing in my logs -- Apache or php.   However, I can catch the error via WP_DEBUG:

`Fatal error: Call to undefined function t() in /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/files/civicrm/ext/cc.tadpole.petitionemail/petitionemail.php on line 198 Call Stack: 0.0003 301280 
1. {main}() /var/www/projects/buildkit/build/wpcv46.dev/wp-admin/admin.php:0 0.2359 46267624 
2. do_action() /var/www/projects/buildkit/build/wpcv46.dev/wp-admin/admin.php:226 0.2359 46269176 
3. call_user_func_array:{/var/www/projects/buildkit/build/wpcv46.dev/wp-includes/plugin.php:496}() /var/www/projects/buildkit/build/wpcv46.dev/wp-includes/plugin.php:496 0.2359 46269480 
4. CiviCRM_For_WordPress->invoke() /var/www/projects/buildkit/build/wpcv46.dev/wp-includes/plugin.php:496 0.2445 47205320 
5. CRM_Core_Invoke::invoke() /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/civicrm/civicrm.php:1189 0.2445 47205608 
6. CRM_Core_Invoke::_invoke() /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:54 0.2489 47502584 
7. CRM_Core_Invoke::runItem() /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:86 0.2503 47643136 
8. CRM_Utils_Wrapper->run() /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:286 0.2664 49867344 
9. CRM_Core_Controller->run() /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php:115 0.2665 49873528 
10. HTML_QuickForm_Page->handle() /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php:353 0.2665 49873728 
11. HTML_QuickForm_Controller->handle() /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php:103 0.2665 49874096 
12. CRM_Core_QuickForm_Action_Display->perform() /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php:203 0.2665 49874848 
13. CRM_Core_Form->buildForm() /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Display.php:94 0.3143 53564576 
14. CRM_Utils_Hook::buildForm() /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php:488 0.3143 53564856 
15. CRM_Utils_Hook_WordPress->invoke() /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php:365 0.3143 53565408 
16. CRM_Utils_Hook->runHooks() /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php:164 0.3143 53567328 
17. petitionemail_civicrm_buildForm() /var/www/projects/buildkit/build/wpcv46.dev/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php:207`

**Comment by josephlacey** [comment]
I think this is just a mistake with the translate string function call.  I added the missing s in the pull request above.  Dana, can you restest and let me know if that doesn't fix it?  I don't have Wordpress installed, so can't test it.

**Comment by danaskallman** [comment]
There was a ts needed for line 202, I just committed here: https://github.com/tadpolecc/cc.tadpole.petitionemail/commit/b7a9d90ad56cd988e88b4057710ddd169438672b

It works with that change. Thanks @kcristiano and @josephlacey
